#----------- Custom Variable Configurations -------------------
APPLICATION:
  MAILING:
    ACCOUNT:
      USERNAME: yash.11717121@gmail.com
      PASSWORD: 
  SECURITY:
    JWT_EXPIRATION: 604800000
    JWT_SECRET: 
  DATABASE:
    USERNAME:
    PASSWORD:
    URL:
  HIBERNATE:
    SHOW_SQL: true
    FORMAT_SQL: true